name: 'Versy Suffix'
description: 'Generate Suffix based on the current branch'

inputs:
  script-branch:
    description: 'Name of the branch in suffix repository'
    required: false
    default: 'main'
outputs:
  suffix:
    description: 'The generated suffix'
    value: ${{ steps.suffix.outputs.suffix }}
runs:
  using: "composite"
  steps:
    - id: suffix
      uses: astorDev/versy/suffix/marketplacing@main
      with:
        script-branch: ${{ inputs.script-branch }}